import type { Lang } from "@/lib/lang";

/** Constellations of the named stars, keyed by IAU abbreviation. */
export const CONSTELLATIONS: Record<string, Record<Lang, string>> = {
  And: { pt: "Andrômeda", en: "Andromeda" },
  Aql: { pt: "Águia", en: "Aquila" },
  Aqr: { pt: "Aquário", en: "Aquarius" },
  Ari: { pt: "Áries", en: "Aries" },
  Aur: { pt: "Cocheiro", en: "Auriga" },
  Boo: { pt: "Boieiro", en: "Boötes" },
  CMa: { pt: "Cão Maior", en: "Canis Major" },
  CMi: { pt: "Cão Menor", en: "Canis Minor" },
  Cap: { pt: "Capricórnio", en: "Capricornus" },
  Car: { pt: "Quilha", en: "Carina" },
  Cen: { pt: "Centauro", en: "Centaurus" },
  Cet: { pt: "Baleia", en: "Cetus" },
  Col: { pt: "Pomba", en: "Columba" },
  CrB: { pt: "Coroa Boreal", en: "Corona Borealis" },
  Cru: { pt: "Cruzeiro do Sul", en: "Crux" },
  Crv: { pt: "Corvo", en: "Corvus" },
  Cyg: { pt: "Cisne", en: "Cygnus" },
  Eri: { pt: "Erídano", en: "Eridanus" },
  Gem: { pt: "Gêmeos", en: "Gemini" },
  Gru: { pt: "Grou", en: "Grus" },
  Hya: { pt: "Hidra", en: "Hydra" },
  Leo: { pt: "Leão", en: "Leo" },
  Lep: { pt: "Lebre", en: "Lepus" },
  Lib: { pt: "Libra", en: "Libra" },
  Lyr: { pt: "Lira", en: "Lyra" },
  Oph: { pt: "Ofiúco", en: "Ophiuchus" },
  Ori: { pt: "Órion", en: "Orion" },
  Pav: { pt: "Pavão", en: "Pavo" },
  Peg: { pt: "Pégaso", en: "Pegasus" },
  Per: { pt: "Perseu", en: "Perseus" },
  Phe: { pt: "Fênix", en: "Phoenix" },
  PsA: { pt: "Peixe Austral", en: "Piscis Austrinus" },
  Pup: { pt: "Popa", en: "Puppis" },
  Sco: { pt: "Escorpião", en: "Scorpius" },
  Ser: { pt: "Serpente", en: "Serpens" },
  Sgr: { pt: "Sagitário", en: "Sagittarius" },
  Tau: { pt: "Touro", en: "Taurus" },
  TrA: { pt: "Triângulo Austral", en: "Triangulum Australe" },
  UMa: { pt: "Ursa Maior", en: "Ursa Major" },
  UMi: { pt: "Ursa Menor", en: "Ursa Minor" },
  Vel: { pt: "Vela", en: "Vela" },
  Vir: { pt: "Virgem", en: "Virgo" },
};
